name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Using the most recent v3

      - uses: actions/setup-node@v3  # Keeping the same version (v3) for stability
        with:
          node-version: '18.*'

      - run: npm install --force

      - run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2  # Using the latest v2 for compatibility

      - uses: actions/upload-artifacts@v3  # Using the latest v3 for potential improvements
        with:
          name: deploy-artifact  # Optional name for the artifact
          path: 'dist/front-web-labstecca-angular'

      - id: deployment
        uses: actions/deploy-pages@v1  # Using the latest v1 for deployments
