name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.*'

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build --prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/front-web-labstecca-angular/browser  # Caminho dos arquivos de build do Angular
          user_name: GitHub Actions
          user_email: actions@github.com
          publish_branch: gh-pages  # Branch do GitHub Pages
          force_orphan: true  # Opcional: criar um branch órfão se não existir
