name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-artifact
          path: dist/front-web-labstecca-angular  # Adjust the path to your built artifacts

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: deploy-artifact  # Ensure this matches the name used in upload-artifact step
